// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/merchant": {
            "post": {
                "description": "This endpoint creates a new merchant",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create Merchant",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateMerchantDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dtos.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entities.Merchant"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/merchant/{id}": {
            "get": {
                "description": "This endpoint retreives a merchant by its id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Get Merchant",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "merchant id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dtos.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entities.Merchant"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/merchant{id}": {
            "delete": {
                "description": "This endpoint deletes a merchant from the system (Soft delete)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Delete Merchant",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "merchant id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.Response"
                        }
                    }
                }
            },
            "patch": {
                "description": "This endpoint updates either name and/or commision from a merchant",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update Merchant",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateMerchantDTO"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "merchant id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dtos.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entities.Merchant"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/transaction": {
            "post": {
                "description": "This endpoint receives a transaction from the request body and adds it to the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create Transaction",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.TransactionDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dtos.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entities.Transaction"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.CreateMerchantDTO": {
            "type": "object",
            "required": [
                "commision",
                "name"
            ],
            "properties": {
                "commision": {
                    "type": "number",
                    "maximum": 100,
                    "minimum": 0
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dtos.ErrorInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "404"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dtos.Meta": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "dtos.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/dtos.ErrorInfo"
                },
                "meta": {
                    "$ref": "#/definitions/dtos.Meta"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "dtos.TransactionDTO": {
            "type": "object",
            "required": [
                "amount",
                "merchantID",
                "userID"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "minimum": 0,
                    "example": 1000
                },
                "merchantID": {
                    "type": "integer",
                    "example": 1
                },
                "userID": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "dtos.UpdateMerchantDTO": {
            "type": "object",
            "properties": {
                "commision": {
                    "type": "number",
                    "maximum": 100,
                    "minimum": 0
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "entities.Merchant": {
            "type": "object",
            "properties": {
                "commision": {
                    "type": "number",
                    "example": 2.5
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "example": "walmart"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "entities.Transaction": {
            "type": "object",
            "properties": {
                "ammount": {
                    "type": "integer",
                    "format": "int64"
                },
                "createdAt": {
                    "type": "string"
                },
                "fee": {
                    "type": "number",
                    "format": "float32"
                },
                "id": {
                    "type": "integer"
                },
                "merchantID": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "API that manages merchants and its transactions.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
